# Generated by Django 5.2.4 on 2025-07-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FrenchBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HindiBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='KannadaBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeluguBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Book',
        ),
    ]
