# Generated by Django 5.2.4 on 2025-07-29 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_englishbook_frenchbook_hindibook_kannadabook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChemicalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CivilBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CseBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EeeBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='MechanicalBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('cover_image', models.URLField(blank=True)),
                ('rating', models.FloatField(default=0.0)),
                ('stock_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
